version: "3.7"
services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://database:5432/tcb
    links:
      - database
    depends_on:
      - database
  database:
    image: mcekovic/uts-database